server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.2.2:3306/CheckInSystem?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.fzu.bean  # 注意：对应实体类的路径

logging:
  config: classpath:logback.xml
